# Script Info -------------------------------------------------------------
# Name:      UO_options.R (Unconventional Oil and Simulation Options Script)
# Author(s): Jon Wilkey
# Contact:   jon.wilkey@gmail.com

# Description -------------------------------------------------------------

# This script creates a list object named "uopt" that contains the options for 
# all the inputs/outputs that control the execution of the UO_main.R script.
# Review each input/output below and change as desired from their base values.


# 1.0 Global Options ------------------------------------------------------

# Define "uopt" list object - this must exist in order to set any other options
uopt <- NULL

# Version number
uopt$ver <- "v2"


# Parameter Space Generation ----------------------------------------------

# Generate latin hypercube sample - Uncomment first line for new sample,
# otherwise load saved one.
parLHS <- randomLHS(n = 1e5, k = 7)#optimumLHS(n = 1e4, k = 7); save(parLHS, file = file.path(path$data, "parLHSv2.rda"))
# load(file.path(path$data, "parLHS.rda"))

# Calcualte parameter values from LHS. Refer to values in
# load(file.path(path$data, hdrill.rda)) as generated by "hdrill cost.R" for
# reference.
uopt$parR <- data.frame(FA =     qunif(parLHS[,1], min = 10,   max = 70),    # Fischer-assay (gal oil / ton shale)
                        OPD =    qunif(parLHS[,2], min = 10e3, max = 100e3), # Oil production rate (BPD)
                        nyear =  round(qunif(parLHS[,3], min = 15,   max = 40)),    # Number of years of full operation
                        MRco =   qunif(parLHS[,4], min = 0.5,  max = 1.5),   # Mine & Retort cap/op expense fraction
                        royalr = qunif(parLHS[,5], min = 0.05, max = 0.20),  # Royalty rate
                        fmaint = qunif(parLHS[,6], min = 0.02, max = 0.115), # Maintence rate (% of CTDC)
                        IRR =    qunif(parLHS[,7], min = 0.10, max = 0.20))  # Internal rate of return

# Remove LHS
remove(parLHS)


# Index Values ------------------------------------------------------------

# CPI adjustment to go from 2012 to 2014 dollars for all terms taken from Market
# Assessment
uopt$cpi <-  236.736/229.594


# Base Mine & Retort Data -------------------------------------------------

uopt$bmr <- data.frame(eff.retort = 0.92,          # Fraction of oil recovered from retorted shale
                       eff.grind =  0.90,          # Fraction of shale recovered from grinder
                       smine =      165700,        # Base shale mined (TPD)
                       sretort =    149130,        # Base shale retorted (TPD)
                       cmine =      465e6,         # Capital cost for mine (1981 USD)
                       cretort =    302e6,         # Capital cost for retort (1981 USD)
                       elec =       277500*24*365, # Electricity usage (kWh/yr)
                       steam =      666*24*365,    # Steam usage (k lb/yr)
                       wcool =      608162,        # Cooling water usage - for mining (kgal/yr)
                       wshale =     895116,        # Water usage - spent shale disposal (kgal/yr)
                       wboil =      2909611,       # Boiler feed water usage - for cooling tower (kgal/yr)
                       wgenR =      1419259,       # Water generated that scales with retorting (kgal/yr)
                       wgenO =      416859,        # Water generated that scales with oil production (kgal/yr)
                       opmine =     77.22e6,       # Mine operating cost (1981 USD/yr)
                       cclean =     90e6,          # Capital cost for retort gas cleaning and upgrading
                       poil =       99170)         # Crude oil production (BPD)



# Labor -------------------------------------------------------------------

# Number of operators per shift
uopt$Nopers <- 54


# Utilities ---------------------------------------------------------------

# Utah 2014 annual average industrial electricity price ($/kWh)
# Data from EIA Average retail price of electricity to ultimate customers: http://www.eia.gov/electricity/data.cfm#sales
uopt$ep <-      0.0607

# Electrity infrastructure
uopt$eline <-   425e3*uopt$cpi # Line cost ($/mi)
uopt$eswitch <- 10e3*uopt$cpi  # Switching gear and tap ($/mi)

# Distance to nearest utility hub (mi)
uopt$hubL <-    6.51

# Water
uopt$wrloss <-  0.03                # Percent water recycling losses
uopt$wmakep <-  50/325.853*uopt$cpi # Makeup water price ($/kgal/yr)
uopt$wcoolp <-  0.075*uopt$cpi      # Cooling water price ($/kgal)
uopt$wboilp <-  1.80*uopt$cpi       # Boiler feed water price ($/kgal)
uopt$pipeL <-   5                   # Water pipeline length (mi)
uopt$elevD <-   711                 # Water pipeline elevation change (ft)
uopt$resS <-    90                  # Reservoir size, in days of makeup water

# Other utility charges
uopt$steamp <-  6.60*uopt$cpi       # Steam price ($/k lb)


# Finance and Econ Terms --------------------------------------------------

# Process Utilization (i.e. number of days per year process is in operation)
uopt$p <- 330

# ACRS 10-yr Depreciation Schedule
uopt$fD <- c(0.1000,
             0.1800,
             0.1440,
             0.1152,
             0.0922,
             0.0737,
             0.0655,
             0.0655,
             0.0656,
             0.0655,
             0.0328)

# Research spending ($/bbl)
uopt$rsp <- 0.741865*uopt$cpi

# Severance taxes
uopt$st.low <-   0.03
uopt$st.high <-  0.05
uopt$st.con <-   0.002
uopt$st.cut.o <- 13

# Income tax rates
uopt$rTS <- 0.05
uopt$rTF <- 0.35

# Labor
uopt$radmin.comp <- 0.0125
