# Script Info -------------------------------------------------------------
# Name:      UO_options.R (Unconventional Oil and Simulation Options Script)
# Author(s): Jon Wilkey
# Contact:   jon.wilkey@gmail.com

# Description -------------------------------------------------------------

# This script creates a list object named "uopt" that contains the options for 
# all the inputs/outputs that control the execution of the UO_main.R script.
# Review each input/output below and change as desired from their base values.


# 1.0 Global Options ------------------------------------------------------

# Define "uopt" list object - this must exist in order to set any other options
uopt <- NULL


# One-time analysis functions ---------------------------------------------


# Parameter Space Generation ----------------------------------------------

# Generate latin hypercube sample - Uncomment first line for new sample,
# otherwise load saved one.
# parLHS <- optimumLHS(n = 4*(2^7), k = 7); save(parLHS, file = file.path(path$data, "parLHS.rda"))
# load(file.path(path$data, "parLHS.rda"))

# Calcualte parameter values from LHS. Refer to values in
# load(file.path(path$data, hdrill.rda)) as generated by "hdrill cost.R" for
# reference.
# uopt$parR <- data.frame(FA =  qunif(parLHS[,1], min = 10,    max = 40),   # Fischer-assay (gal oil / ton shale)
#                         OPD = 
#                         IRR = qunif(parLHS[,6], min = 0.10,  max = 0.40)) # Recovery fraction

uopt$parR <- data.frame(FA = 25,
                        OPD = 47041.76,
                        IRR = 0.1)

# Remove LHS
# remove(parLHS)


# Index Values ------------------------------------------------------------

uopt$cpi <-  236.736 # CPI value for inflation adjustment (average 2014 USD)
uopt$cpiB <- 90.9    # Base CPI value (average 1981 USD)


# Base Mine & Retort Data -------------------------------------------------

uopt$bmr <- data.frame(eff.retort = 0.92,          # Fraction of oil recovered from retorted shale
                       eff.grind =  0.90,          # Fraction of shale recovered from grinder
                       smine =      165700,        # Base shale mined (TPD)
                       sretort =    149130,        # Base shale retorted (TPD)
                       cmine =      465e6,         # Capital cost for mine (1981 USD)
                       cretort =    392e6,         # Capital cost for retort (1981 USD)
                       elec =       277500*24*365, # Electricity usage (kWh/yr)
                       steam =      666*24*365,    # Steam usage (k lb/yr)
                       wcool =      608162,        # Cooling water usage - for mining (kgal/yr)
                       wshale =     895116,        # Water usage - spent shale disposal (kgal/yr)
                       wboil =      2909611,       # Boiler feed water usage - for cooling tower (kgal/yr)
                       wgen =       1836118,       # Water generated (kgal/yr)
                       poil =       99170)         # Crude oil production (BPD)



# Labor -------------------------------------------------------------------

# Number of operators per shift
uopt$Nopers <- 3


# Utilities ---------------------------------------------------------------

# Utah 2014 annual average industrial electricity price ($/kWh)
# Data from EIA Average retail price of electricity to ultimate customers: http://www.eia.gov/electricity/data.cfm#sales
uopt$ep <- 0.0607

# Electrity infrastructure
uopt$eline <-   425e3*(uopt$cpi/232.957) # Line cost ($/mi)
uopt$eswitch <- 10e3*(uopt$cpi/232.957)  # Switching gear and tap ($/mi)

# Distance to nearest utility hub (mi)
uopt$hubL <- 50

# Water
uopt$wrloss <- 0.03 # Percent water recycling losses

# Other utility charges
uopt$steamp <- 6.60 # Steam price (USD) per k lb

# Utility capital

# Finance and Econ Terms --------------------------------------------------

# Minimum construction time (in days)
uopt$tconstr.min <- round(365*9/12)

# ACRS 10-yr Depreciation Schedule
uopt$fD <- c(0.1000,
             0.1800,
             0.1440,
             0.1152,
             0.0922,
             0.0737,
             0.0655,
             0.0655,
             0.0656,
             0.0655,
             0.0328)

# Inflation rate (for adjusting NPV of Depreciation)
uopt$inf <- 0.018

# Royalties
uopt$royalr <- 0.125

# Severance taxes
uopt$st.low <- 0.03
uopt$st.high <- 0.05
uopt$st.con <- 0.002
uopt$st.cut.o <- 13
uopt$st.cut.g <- 1.5

# Income tax rates
uopt$rTS <- 0.05
uopt$rTF <- 0.35

# Labor
uopt$radmin.comp <- 0.0125


